<?php

namespace App\DataFixtures;

use App\Entity\Type;
use App\Entity\Pokemon;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class AppFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        // $product = new Product();
        // $manager->persist($product);
        $array_type = [
            'acier',
            'combat',
            'dragon',
            'eau',
            'electrik',
            'feu',
            'glace',
            'insecte',
            'normal',
            'plante',
            'poison',
            'psy',
            'roche',
            'sol',
            'spectre',
            'vol',
            'fée'
        ];
        $array_pokemon = [
            ['nom'=>'Bulbizarre','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>10,'id_type_2'=>11,'photo'=>'images/pokemon/001.png'],
            ['nom'=>'Herbizarre','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>10,'id_type_2'=>11,'photo'=>'images/pokemon/002.png'],
            ['nom'=>'Florizarre','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>10,'id_type_2'=>11,'photo'=>'images/pokemon/003.png'],
            ['nom'=>'Salamèche','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>6,'id_type_2'=>NULL,'photo'=>'images/pokemon/004.png'],
            ['nom'=>'Reptincel','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>6,'id_type_2'=>NULL,'photo'=>'images/pokemon/005.png'],
            ['nom'=>'Dracaufeu','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>6,'id_type_2'=>16,'photo'=>'images/pokemon/006.png'],
            ['nom'=>'Carapuce','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>4,'id_type_2'=>NULL,'photo'=>'images/pokemon/007.png'],
            ['nom'=>'Carabaffe','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>4,'id_type_2'=>NULL,'photo'=>'images/pokemon/008.png'],
            ['nom'=>'Tortank','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>4,'id_type_2'=>NULL,'photo'=>'images/pokemon/009.png'],
            ['nom'=>'Chenipan','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>8,'id_type_2'=>NULL,'photo'=>'images/pokemon/010.png'],
            ['nom'=>'Chrysacier','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>8,'id_type_2'=>NULL,'photo'=>'images/pokemon/011.png'],
            ['nom'=>'Papilusion','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>8,'id_type_2'=>16,'photo'=>'images/pokemon/012.png'],
            ['nom'=>'Aspicot','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>8,'id_type_2'=>11,'photo'=>'images/pokemon/013.png'],
            ['nom'=>'Coconfort','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>8,'id_type_2'=>11,'photo'=>'images/pokemon/014.png'],
            ['nom'=>'Dardargnan','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>8,'id_type_2'=>11,'photo'=>'images/pokemon/015.png'],
            ['nom'=>'Roucool','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>9,'id_type_2'=>16,'photo'=>'images/pokemon/016.png'],
            ['nom'=>'Roucoups','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>9,'id_type_2'=>16,'photo'=>'images/pokemon/017.png'],
            ['nom'=>'Roucarnage','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>9,'id_type_2'=>16,'photo'=>'images/pokemon/018.png'],
            ['nom'=>'Rattata','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>9,'id_type_2'=>NULL,'photo'=>'images/pokemon/019.png'],
            ['nom'=>'Rattatac','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>9,'id_type_2'=>NULL,'photo'=>'images/pokemon/020.png'],
            ['nom'=>'Piafabec','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>9,'id_type_2'=>16,'photo'=>'images/pokemon/021.png'],
            ['nom'=>'Rapasdepic','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>9,'id_type_2'=>16,'photo'=>'images/pokemon/022.png'],
            ['nom'=>'Abo','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>11,'id_type_2'=>NULL,'photo'=>'images/pokemon/023.png'],
            ['nom'=>'Arbok','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>11,'id_type_2'=>NULL,'photo'=>'images/pokemon/024.png'],
            ['nom'=>'Pikachu','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>5,'id_type_2'=>NULL,'photo'=>'images/pokemon/025.png'],
            ['nom'=>'Raichu','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>5,'id_type_2'=>NULL,'photo'=>'images/pokemon/026.png'],
            ['nom'=>'Sabelette','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>14,'id_type_2'=>NULL,'photo'=>'images/pokemon/027.png'],
            ['nom'=>'Sablaireau','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>14,'id_type_2'=>NULL,'photo'=>'images/pokemon/028.png'],
            ['nom'=>'NidoranF','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>11,'id_type_2'=>NULL,'photo'=>'images/pokemon/029.png'],
            ['nom'=>'Nidorina','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>11,'id_type_2'=>NULL,'photo'=>'images/pokemon/030.png'],
            ['nom'=>'Nidoqueen','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>11,'id_type_2'=>14,'photo'=>'images/pokemon/031.png'],
            ['nom'=>'NidoranF','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>11,'id_type_2'=>NULL,'photo'=>'images/pokemon/032.png'],
            ['nom'=>'Nidorino','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>11,'id_type_2'=>NULL,'photo'=>'images/pokemon/033.png'],
            ['nom'=>'Nidoking','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>11,'id_type_2'=>14,'photo'=>'images/pokemon/034.png'],
            ['nom'=>'Mélofée','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'R','id_type_1'=>17,'id_type_2'=>NULL,'photo'=>'images/pokemon/035.png'],
            ['nom'=>'Mélodelfe','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'R','id_type_1'=>17,'id_type_2'=>NULL,'photo'=>'images/pokemon/036.png'],
            ['nom'=>'Goupix','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>6,'id_type_2'=>NULL,'photo'=>'images/pokemon/037.png'],
            ['nom'=>'Feunard','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>6,'id_type_2'=>NULL,'photo'=>'images/pokemon/038.png'],
            ['nom'=>'Rondoudou','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'R','id_type_1'=>9,'id_type_2'=>17,'photo'=>'images/pokemon/039.png'],
            ['nom'=>'Grodoudou','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'R','id_type_1'=>9,'id_type_2'=>17,'photo'=>'images/pokemon/040.png'],
            ['nom'=>'Nosferapti','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>11,'id_type_2'=>16,'photo'=>'images/pokemon/041.png'],
            ['nom'=>'Nosferalto','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>11,'id_type_2'=>16,'photo'=>'images/pokemon/042.png'],
            ['nom'=>'Mystherbe','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>10,'id_type_2'=>11,'photo'=>'images/pokemon/043.png'],
            ['nom'=>'Ortide','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>10,'id_type_2'=>11,'photo'=>'images/pokemon/044.png'],
            ['nom'=>'Rafflesia','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>10,'id_type_2'=>11,'photo'=>'images/pokemon/045.png'],
            ['nom'=>'Paras','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>8,'id_type_2'=>10,'photo'=>'images/pokemon/046.png'],
            ['nom'=>'Parasect','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>8,'id_type_2'=>10,'photo'=>'images/pokemon/047.png'],
            ['nom'=>'Mimitoss','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>8,'id_type_2'=>11,'photo'=>'images/pokemon/048.png'],
            ['nom'=>'Aéromite','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>8,'id_type_2'=>11,'photo'=>'images/pokemon/049.png'],
            ['nom'=>'Taupiqueur','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>14,'id_type_2'=>NULL,'photo'=>'images/pokemon/050.png'],
            ['nom'=>'Triopikeur','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>14,'id_type_2'=>NULL,'photo'=>'images/pokemon/051.png'],
            ['nom'=>'Miaouss','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>9,'id_type_2'=>NULL,'photo'=>'images/pokemon/052.png'],
            ['nom'=>'Persian','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>9,'id_type_2'=>NULL,'photo'=>'images/pokemon/053.png'],
            ['nom'=>'Psykokwak','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>4,'id_type_2'=>NULL,'photo'=>'images/pokemon/054.png'],
            ['nom'=>'Akwakwak','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>4,'id_type_2'=>NULL,'photo'=>'images/pokemon/055.png'],
            ['nom'=>'Férosinge','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>2,'id_type_2'=>NULL,'photo'=>'images/pokemon/056.png'],
            ['nom'=>'Colossinge','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>2,'id_type_2'=>NULL,'photo'=>'images/pokemon/057.png'],
            ['nom'=>'Caninos','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>6,'id_type_2'=>NULL,'photo'=>'images/pokemon/058.png'],
            ['nom'=>'Arcanin','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>6,'id_type_2'=>NULL,'photo'=>'images/pokemon/059.png'],
            ['nom'=>'Ptitard','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>4,'id_type_2'=>NULL,'photo'=>'images/pokemon/060.png'],
            ['nom'=>'Tétarte','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>4,'id_type_2'=>NULL,'photo'=>'images/pokemon/061.png'],
            ['nom'=>'Tartard','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>4,'id_type_2'=>2,'photo'=>'images/pokemon/062.png'],
            ['nom'=>'Abra','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>12,'id_type_2'=>NULL,'photo'=>'images/pokemon/063.png'],
            ['nom'=>'Kadabra','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>12,'id_type_2'=>NULL,'photo'=>'images/pokemon/064.png'],
            ['nom'=>'Alakazam','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>12,'id_type_2'=>NULL,'photo'=>'images/pokemon/065.png'],
            ['nom'=>'Machoc','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>2,'id_type_2'=>NULL,'photo'=>'images/pokemon/066.png'],
            ['nom'=>'Machopeur','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>2,'id_type_2'=>NULL,'photo'=>'images/pokemon/067.png'],
            ['nom'=>'Mackogneur','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>2,'id_type_2'=>NULL,'photo'=>'images/pokemon/068.png'],
            ['nom'=>'Chétiflor','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>10,'id_type_2'=>11,'photo'=>'images/pokemon/069.png'],
            ['nom'=>'Boustiflor','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>10,'id_type_2'=>11,'photo'=>'images/pokemon/070.png'],
            ['nom'=>'Empiflor','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>10,'id_type_2'=>11,'photo'=>'images/pokemon/071.png'],
            ['nom'=>'Tentacool','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>4,'id_type_2'=>11,'photo'=>'images/pokemon/072.png'],
            ['nom'=>'Tentacruel','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>4,'id_type_2'=>11,'photo'=>'images/pokemon/073.png'],
            ['nom'=>'Racaillou','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>13,'id_type_2'=>14,'photo'=>'images/pokemon/074.png'],
            ['nom'=>'Gravalanch','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>13,'id_type_2'=>14,'photo'=>'images/pokemon/075.png'],
            ['nom'=>'Grolem','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>13,'id_type_2'=>14,'photo'=>'images/pokemon/076.png'],
            ['nom'=>'Ponyta','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>6,'id_type_2'=>NULL,'photo'=>'images/pokemon/077.png'],
            ['nom'=>'Galopa','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>6,'id_type_2'=>NULL,'photo'=>'images/pokemon/078.png'],
            ['nom'=>'Ramoloss','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>4,'id_type_2'=>12,'photo'=>'images/pokemon/079.png'],
            ['nom'=>'Flagadoss','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>4,'id_type_2'=>12,'photo'=>'images/pokemon/080.png'],
            ['nom'=>'Magnéti','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>5,'id_type_2'=>1,'photo'=>'images/pokemon/081.png'],
            ['nom'=>'Magnéton','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>5,'id_type_2'=>1,'photo'=>'images/pokemon/082.png'],
            ['nom'=>'Canarticho','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>9,'id_type_2'=>16,'photo'=>'images/pokemon/083.png'],
            ['nom'=>'Doduo','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>9,'id_type_2'=>16,'photo'=>'images/pokemon/084.png'],
            ['nom'=>'Dodrio','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>9,'id_type_2'=>16,'photo'=>'images/pokemon/085.png'],
            ['nom'=>'Otaria','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>4,'id_type_2'=>NULL,'photo'=>'images/pokemon/086.png'],
            ['nom'=>'Lamantine','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>4,'id_type_2'=>15,'photo'=>'images/pokemon/087.png'],
            ['nom'=>'Tadmorv','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>11,'id_type_2'=>NULL,'photo'=>'images/pokemon/088.png'],
            ['nom'=>'Grotadmorv','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>11,'id_type_2'=>NULL,'photo'=>'images/pokemon/089.png'],
            ['nom'=>'Kokiyas','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>4,'id_type_2'=>NULL,'photo'=>'images/pokemon/090.png'],
            ['nom'=>'Crustabri','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>4,'id_type_2'=>7,'photo'=>'images/pokemon/091.png'],
            ['nom'=>'Fantominus','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>15,'id_type_2'=>11,'photo'=>'images/pokemon/092.png'],
            ['nom'=>'Spectrum','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>15,'id_type_2'=>11,'photo'=>'images/pokemon/093.png'],
            ['nom'=>'Ectoplasma','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>15,'id_type_2'=>11,'photo'=>'images/pokemon/094.png'],
            ['nom'=>'Onix','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>13,'id_type_2'=>14,'photo'=>'images/pokemon/095.png'],
            ['nom'=>'Soporifik','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>12,'id_type_2'=>NULL,'photo'=>'images/pokemon/096.png'],
            ['nom'=>'Hypnomade','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>12,'id_type_2'=>NULL,'photo'=>'images/pokemon/097.png'],
            ['nom'=>'Krabby','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>4,'id_type_2'=>NULL,'photo'=>'images/pokemon/098.png'],
            ['nom'=>'Krabboss','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>4,'id_type_2'=>NULL,'photo'=>'images/pokemon/099.png'],
            ['nom'=>'Voltorbe','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>5,'id_type_2'=>NULL,'photo'=>'images/pokemon/100.png'],
            ['nom'=>'Electrode','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>5,'id_type_2'=>NULL,'photo'=>'images/pokemon/101.png'],
            ['nom'=>'Noeunoeuf','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>10,'id_type_2'=>12,'photo'=>'images/pokemon/102.png'],
            ['nom'=>'Noadkoko','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>10,'id_type_2'=>12,'photo'=>'images/pokemon/103.png'],
            ['nom'=>'Osselait','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>14,'id_type_2'=>NULL,'photo'=>'images/pokemon/104.png'],
            ['nom'=>'Ossatueur','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>14,'id_type_2'=>NULL,'photo'=>'images/pokemon/105.png'],
            ['nom'=>'Kicklee','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>2,'id_type_2'=>NULL,'photo'=>'images/pokemon/106.png'],
            ['nom'=>'Tygnon','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>2,'id_type_2'=>NULL,'photo'=>'images/pokemon/107.png'],
            ['nom'=>'Excelangue','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>9,'id_type_2'=>NULL,'photo'=>'images/pokemon/108.png'],
            ['nom'=>'Smogo','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>11,'id_type_2'=>NULL,'photo'=>'images/pokemon/109.png'],
            ['nom'=>'Smogogo','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>11,'id_type_2'=>NULL,'photo'=>'images/pokemon/110.png'],
            ['nom'=>'Rhinocorne','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>14,'id_type_2'=>13,'photo'=>'images/pokemon/111.png'],
            ['nom'=>'Rhinoféros','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>14,'id_type_2'=>13,'photo'=>'images/pokemon/112.png'],
            ['nom'=>'Leveinard','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'R','id_type_1'=>9,'id_type_2'=>NULL,'photo'=>'images/pokemon/113.png'],
            ['nom'=>'Saquedeneu','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>10,'id_type_2'=>NULL,'photo'=>'images/pokemon/114.png'],
            ['nom'=>'Kangourex','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>9,'id_type_2'=>NULL,'photo'=>'images/pokemon/115.png'],
            ['nom'=>'Hypotrempe','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>4,'id_type_2'=>NULL,'photo'=>'images/pokemon/116.png'],
            ['nom'=>'Hypocéan','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>4,'id_type_2'=>NULL,'photo'=>'images/pokemon/117.png'],
            ['nom'=>'Poissirène','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>4,'id_type_2'=>NULL,'photo'=>'images/pokemon/118.png'],
            ['nom'=>'Poissoroy','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>4,'id_type_2'=>NULL,'photo'=>'images/pokemon/119.png'],
            ['nom'=>'Stari','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>4,'id_type_2'=>NULL,'photo'=>'images/pokemon/120.png'],
            ['nom'=>'Staross','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>4,'id_type_2'=>12,'photo'=>'images/pokemon/121.png'],
            ['nom'=>'M.Mime','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>12,'id_type_2'=>17,'photo'=>'images/pokemon/122.png'],
            ['nom'=>'Insécateur','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>8,'id_type_2'=>16,'photo'=>'images/pokemon/123.png'],
            ['nom'=>'Lippoutou','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>7,'id_type_2'=>12,'photo'=>'images/pokemon/124.png'],
            ['nom'=>'Elektek','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>5,'id_type_2'=>NULL,'photo'=>'images/pokemon/125.png'],
            ['nom'=>'Magmar','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>6,'id_type_2'=>NULL,'photo'=>'images/pokemon/126.png'],
            ['nom'=>'Scarabrute','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>8,'id_type_2'=>NULL,'photo'=>'images/pokemon/127.png'],
            ['nom'=>'Tauros','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>9,'id_type_2'=>NULL,'photo'=>'images/pokemon/128.png'],
            ['nom'=>'Magicarpe','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>4,'id_type_2'=>NULL,'photo'=>'images/pokemon/129.png'],
            ['nom'=>'Léviator','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>4,'id_type_2'=>16,'photo'=>'images/pokemon/130.png'],
            ['nom'=>'Lokhlass','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>4,'id_type_2'=>7,'photo'=>'images/pokemon/131.png'],
            ['nom'=>'Métamorph','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>9,'id_type_2'=>NULL,'photo'=>'images/pokemon/132.png'],
            ['nom'=>'Evoli','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>9,'id_type_2'=>NULL,'photo'=>'images/pokemon/133.png'],
            ['nom'=>'Aquali','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>4,'id_type_2'=>NULL,'photo'=>'images/pokemon/134.png'],
            ['nom'=>'Voltali','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>5,'id_type_2'=>NULL,'photo'=>'images/pokemon/135.png'],
            ['nom'=>'Pyroli','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>6,'id_type_2'=>NULL,'photo'=>'images/pokemon/136.png'],
            ['nom'=>'Porygon','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>9,'id_type_2'=>NULL,'photo'=>'images/pokemon/137.png'],
            ['nom'=>'Amonita','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>13,'id_type_2'=>4,'photo'=>'images/pokemon/138.png'],
            ['nom'=>'Amonistar','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>13,'id_type_2'=>4,'photo'=>'images/pokemon/139.png'],
            ['nom'=>'Kabuto','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>13,'id_type_2'=>4,'photo'=>'images/pokemon/140.png'],
            ['nom'=>'Kabutops','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>13,'id_type_2'=>4,'photo'=>'images/pokemon/141.png'],
            ['nom'=>'Ptéra','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>13,'id_type_2'=>16,'photo'=>'images/pokemon/142.png'],
            ['nom'=>'Ronflex','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>9,'id_type_2'=>NULL,'photo'=>'images/pokemon/143.png'],
            ['nom'=>'Artikodin','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>7,'id_type_2'=>16,'photo'=>'images/pokemon/144.png'],
            ['nom'=>'Electhor','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>5,'id_type_2'=>16,'photo'=>'images/pokemon/145.png'],
            ['nom'=>'Sulfura','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>6,'id_type_2'=>16,'photo'=>'images/pokemon/146.png'],
            ['nom'=>'Minidraco','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>3,'id_type_2'=>NULL,'photo'=>'images/pokemon/147.png'],
            ['nom'=>'Draco','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>3,'id_type_2'=>NULL,'photo'=>'images/pokemon/148.png'],
            ['nom'=>'Dracolosse','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>3,'id_type_2'=>16,'photo'=>'images/pokemon/149.png'],
            ['nom'=>'Mewtwo','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>12,'id_type_2'=>NULL,'photo'=>'images/pokemon/150.png'],
            ['nom'=>'Mew','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>12,'id_type_2'=>NULL,'photo'=>'images/pokemon/151.png']
        ];
        foreach($array_type as $type){
            $new_type = new Type();
            $new_type->setNom($type);
            $manager->persist($new_type);
        }
        foreach($array_pokemon as $pokemon){
            $new_pokemon = new Pokemon();
            $new_pokemon->setNom($pokemon['nom']);
            $new_pokemon->setIsEvolution($pokemon['is_evolution']);
            $new_pokemon->setIsStarter($pokemon['is_starter']);
            $new_pokemon->setTypeCourbeNiveau($pokemon['type_courbe']);
            $new_pokemon->setIdType1($pokemon['id_type_1']);
            $new_pokemon->setIdType2($pokemon['id_type_2']);
            $new_pokemon->setPhoto($pokemon['photo']);
            $new_pokemon->setCanEvolve($pokemon['can_evolve']);
            $manager->persist($new_pokemon);
        }
        $manager->flush();
    }
}
