<?php

namespace App\DataFixtures;

use App\Entity\Pokemon;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class PokemonFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $array_pokemon = [
            ['nom'=>'Bulbizarre','is_evolution'=>false,'is_starter'=>true,'type_courbe'=>'P','id_type_1'=>'plante','id_type_2'=>'poison','photo'=>'images/pokemon/001.png','can_evolve'=>true,'niveau_evolution'=>'16'],
            ['nom'=>'Herbizarre','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'plante','id_type_2'=>'poison','photo'=>'images/pokemon/002.png','can_evolve'=>true,'niveau_evolution'=>32],
            ['nom'=>'Florizarre','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'plante','id_type_2'=>'poison','photo'=>'images/pokemon/003.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Salamèche','is_evolution'=>false,'is_starter'=>true,'type_courbe'=>'P','id_type_1'=>'feu','id_type_2'=>NULL,'photo'=>'images/pokemon/004.png','can_evolve'=>true,'niveau_evolution'=>16],
            ['nom'=>'Reptincel','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'feu','id_type_2'=>NULL,'photo'=>'images/pokemon/005.png','can_evolve'=>true,'niveau_evolution'=>36],
            ['nom'=>'Dracaufeu','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'feu','id_type_2'=>'vol','photo'=>'images/pokemon/006.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Carapuce','is_evolution'=>false,'is_starter'=>true,'type_courbe'=>'P','id_type_1'=>'eau','id_type_2'=>NULL,'photo'=>'images/pokemon/007.png','can_evolve'=>true,'niveau_evolution'=>16],
            ['nom'=>'Carabaffe','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'eau','id_type_2'=>NULL,'photo'=>'images/pokemon/008.png','can_evolve'=>true,'niveau_evolution'=>36],
            ['nom'=>'Tortank','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'eau','id_type_2'=>NULL,'photo'=>'images/pokemon/009.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Chenipan','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'insecte','id_type_2'=>NULL,'photo'=>'images/pokemon/010.png','can_evolve'=>true,'niveau_evolution'=>7],
            ['nom'=>'Chrysacier','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'insecte','id_type_2'=>NULL,'photo'=>'images/pokemon/011.png','can_evolve'=>true,'niveau_evolution'=>10],
            ['nom'=>'Papilusion','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'insecte','id_type_2'=>'vol','photo'=>'images/pokemon/012.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Aspicot','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'insecte','id_type_2'=>'poison','photo'=>'images/pokemon/013.png','can_evolve'=>true,'niveau_evolution'=>7],
            ['nom'=>'Coconfort','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'insecte','id_type_2'=>'poison','photo'=>'images/pokemon/014.png','can_evolve'=>true,'niveau_evolution'=>10],
            ['nom'=>'Dardargnan','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'insecte','id_type_2'=>'poison','photo'=>'images/pokemon/015.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Roucool','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'normal','id_type_2'=>'vol','photo'=>'images/pokemon/016.png','can_evolve'=>true,'niveau_evolution'=>18],
            ['nom'=>'Roucoups','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'normal','id_type_2'=>'vol','photo'=>'images/pokemon/017.png','can_evolve'=>true,'niveau_evolution'=>36],
            ['nom'=>'Roucarnage','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'normal','id_type_2'=>'vol','photo'=>'images/pokemon/018.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Rattata','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'normal','id_type_2'=>NULL,'photo'=>'images/pokemon/019.png','can_evolve'=>true,'niveau_evolution'=>20],
            ['nom'=>'Rattatac','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'normal','id_type_2'=>NULL,'photo'=>'images/pokemon/020.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Piafabec','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'normal','id_type_2'=>'vol','photo'=>'images/pokemon/021.png','can_evolve'=>true,'niveau_evolution'=>20],
            ['nom'=>'Rapasdepic','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'normal','id_type_2'=>'vol','photo'=>'images/pokemon/022.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Abo','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'poison','id_type_2'=>NULL,'photo'=>'images/pokemon/023.png','can_evolve'=>true,'niveau_evolution'=>22],
            ['nom'=>'Arbok','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'poison','id_type_2'=>NULL,'photo'=>'images/pokemon/024.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Pikachu','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'electrik','id_type_2'=>NULL,'photo'=>'images/pokemon/025.png','can_evolve'=>true,'niveau_evolution'=>25],
            ['nom'=>'Raichu','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'electrik','id_type_2'=>NULL,'photo'=>'images/pokemon/026.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Sabelette','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'sol','id_type_2'=>NULL,'photo'=>'images/pokemon/027.png','can_evolve'=>true,'niveau_evolution'=>22],
            ['nom'=>'Sablaireau','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'sol','id_type_2'=>NULL,'photo'=>'images/pokemon/028.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'NidoranF','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'poison','id_type_2'=>NULL,'photo'=>'images/pokemon/029.png','can_evolve'=>true,'niveau_evolution'=>16],
            ['nom'=>'Nidorina','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'poison','id_type_2'=>NULL,'photo'=>'images/pokemon/030.png','can_evolve'=>true,'niveau_evolution'=>32],
            ['nom'=>'Nidoqueen','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'poison','id_type_2'=>'sol','photo'=>'images/pokemon/031.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'NidoranM','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'poison','id_type_2'=>NULL,'photo'=>'images/pokemon/032.png','can_evolve'=>true,'niveau_evolution'=>16],
            ['nom'=>'Nidorino','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'poison','id_type_2'=>NULL,'photo'=>'images/pokemon/033.png','can_evolve'=>true,'niveau_evolution'=>32],
            ['nom'=>'Nidoking','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'poison','id_type_2'=>'sol','photo'=>'images/pokemon/034.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Mélofée','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'R','id_type_1'=>'fée','id_type_2'=>NULL,'photo'=>'images/pokemon/035.png','can_evolve'=>true,'niveau_evolution'=>25],
            ['nom'=>'Mélodelfe','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'R','id_type_1'=>'fée','id_type_2'=>NULL,'photo'=>'images/pokemon/036.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Goupix','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'feu','id_type_2'=>NULL,'photo'=>'images/pokemon/037.png','can_evolve'=>true,'niveau_evolution'=>25],
            ['nom'=>'Feunard','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'feu','id_type_2'=>NULL,'photo'=>'images/pokemon/038.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Rondoudou','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'R','id_type_1'=>'normal','id_type_2'=>'fée','photo'=>'images/pokemon/039.png','can_evolve'=>true,'niveau_evolution'=>22],
            ['nom'=>'Grodoudou','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'R','id_type_1'=>'normal','id_type_2'=>'fée','photo'=>'images/pokemon/040.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Nosferapti','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'poison','id_type_2'=>'vol','photo'=>'images/pokemon/041.png','can_evolve'=>true,'niveau_evolution'=>22],
            ['nom'=>'Nosferalto','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'poison','id_type_2'=>'vol','photo'=>'images/pokemon/042.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Mystherbe','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'plante','id_type_2'=>'poison','photo'=>'images/pokemon/043.png','can_evolve'=>true,'niveau_evolution'=>21],
            ['nom'=>'Ortide','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'plante','id_type_2'=>'poison','photo'=>'images/pokemon/044.png','can_evolve'=>true,'niveau_evolution'=>32],
            ['nom'=>'Rafflesia','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'plante','id_type_2'=>'poison','photo'=>'images/pokemon/045.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Paras','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'insecte','id_type_2'=>'plante','photo'=>'images/pokemon/046.png','can_evolve'=>true,'niveau_evolution'=>24],
            ['nom'=>'Parasect','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'insecte','id_type_2'=>'plante','photo'=>'images/pokemon/047.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Mimitoss','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'insecte','id_type_2'=>'poison','photo'=>'images/pokemon/048.png','can_evolve'=>true,'niveau_evolution'=>31],
            ['nom'=>'Aéromite','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'insecte','id_type_2'=>'poison','photo'=>'images/pokemon/049.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Taupiqueur','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'sol','id_type_2'=>NULL,'photo'=>'images/pokemon/050.png','can_evolve'=>true,'niveau_evolution'=>26],
            ['nom'=>'Triopikeur','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'sol','id_type_2'=>NULL,'photo'=>'images/pokemon/051.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Miaouss','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'normal','id_type_2'=>NULL,'photo'=>'images/pokemon/052.png','can_evolve'=>true,'niveau_evolution'=>28],
            ['nom'=>'Persian','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'normal','id_type_2'=>NULL,'photo'=>'images/pokemon/053.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Psykokwak','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'eau','id_type_2'=>NULL,'photo'=>'images/pokemon/054.png','can_evolve'=>true,'niveau_evolution'=>33],
            ['nom'=>'Akwakwak','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'eau','id_type_2'=>NULL,'photo'=>'images/pokemon/055.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Férosinge','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'combat','id_type_2'=>NULL,'photo'=>'images/pokemon/056.png','can_evolve'=>true,'niveau_evolution'=>28],
            ['nom'=>'Colossinge','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'combat','id_type_2'=>NULL,'photo'=>'images/pokemon/057.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Caninos','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'feu','id_type_2'=>NULL,'photo'=>'images/pokemon/058.png','can_evolve'=>true,'niveau_evolution'=>25],
            ['nom'=>'Arcanin','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'feu','id_type_2'=>NULL,'photo'=>'images/pokemon/059.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Ptitard','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'eau','id_type_2'=>NULL,'photo'=>'images/pokemon/060.png','can_evolve'=>true,'niveau_evolution'=>25],
            ['nom'=>'Tétarte','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'eau','id_type_2'=>NULL,'photo'=>'images/pokemon/061.png','can_evolve'=>true,'niveau_evolution'=>40],
            ['nom'=>'Tartard','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'eau','id_type_2'=>'combat','photo'=>'images/pokemon/062.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Abra','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'psy','id_type_2'=>NULL,'photo'=>'images/pokemon/063.png','can_evolve'=>true,'niveau_evolution'=>16],
            ['nom'=>'Kadabra','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'psy','id_type_2'=>NULL,'photo'=>'images/pokemon/064.png','can_evolve'=>true,'niveau_evolution'=>36],
            ['nom'=>'Alakazam','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'psy','id_type_2'=>NULL,'photo'=>'images/pokemon/065.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Machoc','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'combat','id_type_2'=>NULL,'photo'=>'images/pokemon/066.png','can_evolve'=>true,'niveau_evolution'=>28],
            ['nom'=>'Machopeur','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'combat','id_type_2'=>NULL,'photo'=>'images/pokemon/067.png','can_evolve'=>true,'niveau_evolution'=>40],
            ['nom'=>'Mackogneur','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'combat','id_type_2'=>NULL,'photo'=>'images/pokemon/068.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Chétiflor','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'plante','id_type_2'=>'poison','photo'=>'images/pokemon/069.png','can_evolve'=>true,'niveau_evolution'=>21],
            ['nom'=>'Boustiflor','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'plante','id_type_2'=>'poison','photo'=>'images/pokemon/070.png','can_evolve'=>true,'niveau_evolution'=>31],
            ['nom'=>'Empiflor','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'plante','id_type_2'=>'poison','photo'=>'images/pokemon/071.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Tentacool','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'eau','id_type_2'=>'poison','photo'=>'images/pokemon/072.png','can_evolve'=>true,'niveau_evolution'=>30],
            ['nom'=>'Tentacruel','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'eau','id_type_2'=>'poison','photo'=>'images/pokemon/073.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Racaillou','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'roche','id_type_2'=>'sol','photo'=>'images/pokemon/074.png','can_evolve'=>true,'niveau_evolution'=>25],
            ['nom'=>'Gravalanch','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'roche','id_type_2'=>'sol','photo'=>'images/pokemon/075.png','can_evolve'=>true,'niveau_evolution'=>36],
            ['nom'=>'Grolem','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'roche','id_type_2'=>'sol','photo'=>'images/pokemon/076.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Ponyta','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'feu','id_type_2'=>NULL,'photo'=>'images/pokemon/077.png','can_evolve'=>true,'niveau_evolution'=>25],
            ['nom'=>'Galopa','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'feu','id_type_2'=>NULL,'photo'=>'images/pokemon/078.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Ramoloss','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'eau','id_type_2'=>'psy','photo'=>'images/pokemon/079.png','can_evolve'=>true,'niveau_evolution'=>37],
            ['nom'=>'Flagadoss','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'eau','id_type_2'=>'psy','photo'=>'images/pokemon/080.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Magnéti','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'electrik','id_type_2'=>'acier','photo'=>'images/pokemon/081.png','can_evolve'=>true,'niveau_evolution'=>30],
            ['nom'=>'Magnéton','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'electrik','id_type_2'=>'acier','photo'=>'images/pokemon/082.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Canarticho','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'normal','id_type_2'=>'vol','photo'=>'images/pokemon/083.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Doduo','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'normal','id_type_2'=>'vol','photo'=>'images/pokemon/084.png','can_evolve'=>true,'niveau_evolution'=>31],
            ['nom'=>'Dodrio','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'normal','id_type_2'=>'vol','photo'=>'images/pokemon/085.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Otaria','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'eau','id_type_2'=>NULL,'photo'=>'images/pokemon/086.png','can_evolve'=>true,'niveau_evolution'=>34],
            ['nom'=>'Lamantine','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'eau','id_type_2'=>'spectre','photo'=>'images/pokemon/087.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Tadmorv','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'poison','id_type_2'=>NULL,'photo'=>'images/pokemon/088.png','can_evolve'=>true,'niveau_evolution'=>38],
            ['nom'=>'Grotadmorv','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'poison','id_type_2'=>NULL,'photo'=>'images/pokemon/089.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Kokiyas','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'eau','id_type_2'=>NULL,'photo'=>'images/pokemon/090.png','can_evolve'=>true,'niveau_evolution'=>30],
            ['nom'=>'Crustabri','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'eau','id_type_2'=>'glace','photo'=>'images/pokemon/091.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Fantominus','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'spectre','id_type_2'=>'poison','photo'=>'images/pokemon/092.png','can_evolve'=>true,'niveau_evolution'=>25],
            ['nom'=>'Spectrum','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'spectre','id_type_2'=>'poison','photo'=>'images/pokemon/093.png','can_evolve'=>true,'niveau_evolution'=>36],
            ['nom'=>'Ectoplasma','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'spectre','id_type_2'=>'poison','photo'=>'images/pokemon/094.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Onix','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'roche','id_type_2'=>'sol','photo'=>'images/pokemon/095.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Soporifik','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'psy','id_type_2'=>NULL,'photo'=>'images/pokemon/096.png','can_evolve'=>true,'niveau_evolution'=>26],
            ['nom'=>'Hypnomade','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'psy','id_type_2'=>NULL,'photo'=>'images/pokemon/097.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Krabby','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'eau','id_type_2'=>NULL,'photo'=>'images/pokemon/098.png','can_evolve'=>true,'niveau_evolution'=>28],
            ['nom'=>'Krabboss','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'eau','id_type_2'=>NULL,'photo'=>'images/pokemon/099.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Voltorbe','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'electrik','id_type_2'=>NULL,'photo'=>'images/pokemon/100.png','can_evolve'=>true,'niveau_evolution'=>30],
            ['nom'=>'Electrode','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'electrik','id_type_2'=>NULL,'photo'=>'images/pokemon/101.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Noeunoeuf','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'plante','id_type_2'=>'psy','photo'=>'images/pokemon/102.png','can_evolve'=>true,'niveau_evolution'=>31],
            ['nom'=>'Noadkoko','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'plante','id_type_2'=>'psy','photo'=>'images/pokemon/103.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Osselait','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'sol','id_type_2'=>NULL,'photo'=>'images/pokemon/104.png','can_evolve'=>true,'niveau_evolution'=>28],
            ['nom'=>'Ossatueur','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'sol','id_type_2'=>NULL,'photo'=>'images/pokemon/105.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Kicklee','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'combat','id_type_2'=>NULL,'photo'=>'images/pokemon/106.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Tygnon','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'combat','id_type_2'=>NULL,'photo'=>'images/pokemon/107.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Excelangue','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'normal','id_type_2'=>NULL,'photo'=>'images/pokemon/108.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Smogo','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'poison','id_type_2'=>NULL,'photo'=>'images/pokemon/109.png','can_evolve'=>true,'niveau_evolution'=>35],
            ['nom'=>'Smogogo','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'poison','id_type_2'=>NULL,'photo'=>'images/pokemon/110.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Rhinocorne','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'sol','id_type_2'=>'roche','photo'=>'images/pokemon/111.png','can_evolve'=>true,'niveau_evolution'=>42],
            ['nom'=>'Rhinoféros','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'sol','id_type_2'=>'roche','photo'=>'images/pokemon/112.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Leveinard','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'R','id_type_1'=>'normal','id_type_2'=>NULL,'photo'=>'images/pokemon/113.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Saquedeneu','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'plante','id_type_2'=>NULL,'photo'=>'images/pokemon/114.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Kangourex','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'normal','id_type_2'=>NULL,'photo'=>'images/pokemon/115.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Hypotrempe','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'eau','id_type_2'=>NULL,'photo'=>'images/pokemon/116.png','can_evolve'=>true,'niveau_evolution'=>32],
            ['nom'=>'Hypocéan','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'eau','id_type_2'=>NULL,'photo'=>'images/pokemon/117.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Poissirène','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'eau','id_type_2'=>NULL,'photo'=>'images/pokemon/118.png','can_evolve'=>true,'niveau_evolution'=>33],
            ['nom'=>'Poissoroy','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'eau','id_type_2'=>NULL,'photo'=>'images/pokemon/119.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Stari','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'eau','id_type_2'=>NULL,'photo'=>'images/pokemon/120.png','can_evolve'=>true,'niveau_evolution'=>28],
            ['nom'=>'Staross','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'eau','id_type_2'=>'psy','photo'=>'images/pokemon/121.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'M.Mime','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'psy','id_type_2'=>'fée','photo'=>'images/pokemon/122.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Insécateur','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'insecte','id_type_2'=>'vol','photo'=>'images/pokemon/123.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Lippoutou','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'glace','id_type_2'=>'psy','photo'=>'images/pokemon/124.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Elektek','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'electrik','id_type_2'=>NULL,'photo'=>'images/pokemon/125.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Magmar','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'feu','id_type_2'=>NULL,'photo'=>'images/pokemon/126.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Scarabrute','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'insecte','id_type_2'=>NULL,'photo'=>'images/pokemon/127.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Tauros','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'normal','id_type_2'=>NULL,'photo'=>'images/pokemon/128.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Magicarpe','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'eau','id_type_2'=>NULL,'photo'=>'images/pokemon/129.png','can_evolve'=>true,'niveau_evolution'=>20],
            ['nom'=>'Léviator','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'eau','id_type_2'=>'vol','photo'=>'images/pokemon/130.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Lokhlass','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'eau','id_type_2'=>'glace','photo'=>'images/pokemon/131.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Métamorph','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'normal','id_type_2'=>NULL,'photo'=>'images/pokemon/132.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Evoli','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'normal','id_type_2'=>NULL,'photo'=>'images/pokemon/133.png','can_evolve'=>true,'niveau_evolution'=>25],
            ['nom'=>'Aquali','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'eau','id_type_2'=>NULL,'photo'=>'images/pokemon/134.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Voltali','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'electrik','id_type_2'=>NULL,'photo'=>'images/pokemon/135.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Pyroli','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'feu','id_type_2'=>NULL,'photo'=>'images/pokemon/136.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Porygon','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'normal','id_type_2'=>NULL,'photo'=>'images/pokemon/137.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Amonita','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'roche','id_type_2'=>'eau','photo'=>'images/pokemon/138.png','can_evolve'=>true,'niveau_evolution'=>16,'niveau_evolution'=>40],
            ['nom'=>'Amonistar','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'roche','id_type_2'=>'eau','photo'=>'images/pokemon/139.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Kabuto','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'roche','id_type_2'=>'eau','photo'=>'images/pokemon/140.png','can_evolve'=>true,'niveau_evolution'=>40],
            ['nom'=>'Kabutops','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'M','id_type_1'=>'roche','id_type_2'=>'eau','photo'=>'images/pokemon/141.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Ptéra','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'roche','id_type_2'=>'vol','photo'=>'images/pokemon/142.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Ronflex','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'normal','id_type_2'=>NULL,'photo'=>'images/pokemon/143.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Artikodin','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'glace','id_type_2'=>'vol','photo'=>'images/pokemon/144.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Electhor','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'electrik','id_type_2'=>'vol','photo'=>'images/pokemon/145.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Sulfura','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'feu','id_type_2'=>'vol','photo'=>'images/pokemon/146.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Minidraco','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'dragon','id_type_2'=>NULL,'photo'=>'images/pokemon/147.png','can_evolve'=>true,'niveau_evolution'=>30],
            ['nom'=>'Draco','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'dragon','id_type_2'=>NULL,'photo'=>'images/pokemon/148.png','can_evolve'=>true,'niveau_evolution'=>55],
            ['nom'=>'Dracolosse','is_evolution'=>true,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'dragon','id_type_2'=>'vol','photo'=>'images/pokemon/149.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Mewtwo','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'L','id_type_1'=>'psy','id_type_2'=>NULL,'photo'=>'images/pokemon/150.png','can_evolve'=>false,'niveau_evolution'=>NULL],
            ['nom'=>'Mew','is_evolution'=>false,'is_starter'=>false,'type_courbe'=>'P','id_type_1'=>'psy','id_type_2'=>NULL,'photo'=>'images/pokemon/151.png','can_evolve'=>false,'niveau_evolution'=>NULL]
        ];
        $i = 1;
        foreach($array_pokemon as $pokemon){
            $new_pokemon = new Pokemon();
            $new_pokemon->setNom($pokemon['nom']);
            $new_pokemon->setIsEvolution($pokemon['is_evolution']);
            $new_pokemon->setIsStarter($pokemon['is_starter']);
            $new_pokemon->setTypeCourbeNiveau($pokemon['type_courbe']);
            $type1 = $this->getReference($pokemon['id_type_1']);
            $new_pokemon->setIdType1($type1);
            if($pokemon['id_type_2']!=NULL){
                $type2 = $this->getReference($pokemon['id_type_2']);
                $new_pokemon->setIdType2($type2);
            }
            $new_pokemon->setPhoto($pokemon['photo']);
            $new_pokemon->setCanEvolve($pokemon['can_evolve']);
            $new_pokemon->setNiveauEvolution($pokemon['niveau_evolution']);
            $this->addReference('pokemon'.$i,$new_pokemon);
            $i = $i+1;
            $manager->persist($new_pokemon);
        }

        $manager->flush();
    }
}
